name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ses-gpt-app" #Must be unique in Heroku
          heroku_email: "jfitzdevelop@gmail.com"
          appdir: "server"
          procfile: "web: npm run build && node index.js"
        env:
          HD_NODE_ENV: "production"
